v47-client/src/components/productpage/LeftNav/LeftNav.jsx, v47-client/src/components/productpage/modals/Add.jsx, v47-client/src/pages/ProductPage.jsx
=> made the add activity button more functional 

v47-client/src/App.jsx, v47-client/src/components/navbar/DarkMode.jsx, v47-client/src/components/productpage/Header.jsx, v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/LeftNav/LeftNav.jsx, v47-client/src/components/productpage/Main.jsx, v47-client/src/pages/Landing.jsx, v47-client/src/pages/ProductPage.jsx, v47-client/src/styles/global.css
Task:
- implemented header on product page
- implemented dark mode as global variable
How:
- for the header i re-used darkmode/lightmode from nav to be implemented into productpage, title has been changed from static to dynamic via onclick on left nav
- for darkmode i just simply changed the location of usestate/context, still need to update nav and delete old usestate/context for more reusability. 
Darkmode:
old header: 
loading:
new header:
=> implemented header and change location of darkmode

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/LeftNav/LeftNav.jsx
TASK:
- changed 'add new activity' button to 'add new category'
- added + button for 'add new activity'
- added activities to mobile menu
- changed icons and styles to hopefully look cleaner
=> Jess - style left nav

v47-client/src/components/productpage/Header.jsx
animated hamburger in product page header
=> animate hamburger

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx
in left nav:
- animate chevron
- changed delete icon for activity, 
- and fixed tailwind
=> jess- styling

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/LeftNav/LeftNav.jsx, v47-client/src/components/productpage/modals/Add.jsx, v47-client/src/components/productpage/modals/AddNewCategory.jsx, v47-client/src/components/productpage/modals/Delete.jsx, v47-client/src/pages/ProductPage.jsx
=> Implement Delete, Add. AddNewCategory functionality in leftNav component

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/LeftNav/LeftNav.jsx
=> Jess - add edit icon

v47-client/src/pages/Footer.jsx, v47-client/src/pages/Landing.jsx, v47-client/src/pages/Logout.jsx, v47-client/src/pages/ProductPage.jsx, v47-client/src/pages/Signup.jsx
###restored deleted functions
###add button action in product page
###landing page nav bar signup/login buttons has been changed
=> restore deleted functions - sky

v47-client/src/data.json
=> jess - add column key to json

v47-client/src/components/productpage/modals/Delete.jsx
=> bringing the Delete component to the front

v47-client/package-lock.json, v47-client/package.json, v47-client/public/index.html, v47-client/src/components/productpage/main/Main.jsx, v47-client/src/components/productpage/main/TaskList.jsx, v47-client/src/components/productpage/modals/Add.jsx, v47-client/src/pages/Landing.jsx
=> implemented aos library and did landing animations

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx
add fade in animation to left nav
=> jess - add animation to left nav

v47-client/src/App.jsx, v47-client/src/components/navbar/HambergerMenu.jsx, v47-client/src/components/navbar/Navbar.jsx, v47-client/src/pages/PricingPage.jsx
Pricing page ui (ui only, not hooked up to stripe)
=> Jess - pricing page ui

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/LeftNav/LeftNav.jsx, v47-client/src/pages/ProductPage.jsx
mobile menu closes when clicked outside
=> Jess - mobile menu close on outside click

jsconfig.json, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/LeftNav/LeftNav.jsx, v47-client/src/components/productpage/main/Main.jsx, v47-client/src/components/productpage/main/TaskList.jsx, v47-client/src/components/productpage/modals/edit/EditCategoryModal.jsx, v47-client/src/data.json, v47-client/src/pages/ProductPage.jsx, v47-client/src/styles/global.css
implemented structure for columns still need work on design
=> implemented start for taskboard 'feel'

v47-client/src/components/landing/features/Features.jsx, v47-client/src/components/landing/features/Icons.jsx, v47-client/src/components/landing/features/Stats.jsx, v47-client/src/pages/Landing.jsx
=> Jess - features component

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/LeftNav/LeftNav.jsx
add scrollbar and hover effect to left nav
=> jess - fix tailwind

v47-client/src/components/landing/features/Stat.jsx, v47-client/src/components/landing/features/Stats.jsx, v47-client/src/components/landing/features/useScrollTriggeredCountUp.js
- animate number count for  stats
- add gradient to number
=> jess - animate number count

v47-client/src/components/landing/features/Features.jsx
add fade in for features with aos
=> jess -  fade in features

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/modals/Delete.jsx, v47-client/src/lib/helpers/capitalizeEachWord.js
added deleted logic for delete category and delete activity
=> jess - delete logic for delete category and delete activity

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/modals/Delete.jsx, v47-client/src/lib/helpers/capitalizeEachWord.js
Reverts chingu-voyages/v47-tier2-team-10#62
=> Revert "jess - delete logic for delete category and delete activity"

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/modals/Delete.jsx, v47-client/src/lib/helpers/capitalizeEachWord.js
delete category logic and delete activity logic
=> jess - delete category and activity logic

v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx
on mobile, menu closes when delete modal opens
=> jess - close menu on mobile when delete modal open

v47-client/src/components/productpage/LeftNav/LeftNav.jsx, v47-client/src/components/productpage/modals/AddNewCategory.jsx
=> add new category logic

v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/LeftNav/LeftNav.jsx, v47-client/src/components/productpage/modals/add/AddNewActivity.jsx, v47-client/src/components/productpage/modals/add/AddNewCategory.jsx
=> new activity logic

v47-client/src/components/productpage/modals/edit/EditCategoryModal.jsx
changed headerText  from 'task' to 'category' in edit category modal component
=> changed headerText  from 'task' to 'category'

v47-client/src/App.jsx, v47-client/src/components/landing/features/Features.jsx, v47-client/src/components/landing/features/Icons.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/header/Header.jsx
bugs fixed:
- our features color changed to green (features)
- sub heading changed to text-[16px] (features)
- change color when active (left panel category's)
- left panel burger menu has error when opened, (needs background as fixed)
=> Bugs fixed

v47-client/src/components/landing/features/Icons.jsx, v47-client/src/components/productpage/LeftNav/Activity.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/header/Header.jsx, v47-client/src/pages/PricingPage.jsx
=> dark icons

v47-client/src/components/landing/teamInfo/TeamInfo.jsx, v47-client/src/components/landing/testimonials/Testimonials.jsx, v47-client/src/components/productpage/LeftNav/Category.jsx, v47-client/src/components/productpage/header/Header.jsx, v47-client/src/components/productpage/modals/edit/EditActivityModal.jsx, v47-client/src/components/productpage/modals/edit/EditCategoryModal.jsx, v47-client/src/components/productpage/weather/Weather.jsx
Bug UI changes:
- fix add category logic, was showing undefined when there was no text. need to refactor to make more resusable though,
- centre and change heading color for testimonal and team info
- spacing for weather; can also add icon if want
=> Bug UI changes
